name: Hourly Request to Vercel

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  call-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        env:
          APP_URL: ${{ secrets.APP_URL }}

        run: |
          echo "Using APP_URL: $APP_URL"
          curl -v "$APP_URL/api/line_notifications"
