name: Hourly Request to Vercel

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  call-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        env:
          APP_URL: ${ secrets.APP_URL }
        run: |
          curl -v -X GET "$APP_URL/api/line_notifications?nocache=$(date +%s)"
