name: line notififications

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  call-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        env:
          APP_URL: ${{ secrets.APP_URL }}

        run: |
          curl -v -X POST "$APP_URL/api/line_notifications"
